"""CrochetPARADE DSL 导出器（外部对标研究的 P1 建议）。

把本项目的逐圈图解翻译为 CrochetPARADE（crochetparade.org）的文本语法，
供用户粘贴到其网页应用获得：可旋转 3D 模型、"过松/过紧针目"物理分析、
逐针动画与 Blender 可导入的 3D 文件——本项目代数自检之外的独立验证层
（G4 实体试钩前的最近似替代）。

语法依据（逐条核对过的官方来源，勿凭记忆改动）：
- 每个新行 = 新的一圈；`ring` 单独一行表示魔法环（无固定默认针数）；
- `stitchNinc` / `stitchNtog`：N 针并 1 针目 / 1 针目放 N 针
  （如 `sc6inc` = 一针目里 6 短针，`sc2tog` = 2 针并 1）；
- `Nstitch` = 重复 N 次（`8sc`）；`N[...]` = 方括号组重复 N 次
  （`6[sc,sc2inc]`）；
- `start_anew`：下一针与前一针无连接（开始新部件）；
- `COLOR: <hex>` 指令作用于其后针目；`#` 行注释。
官方手册：https://crochetparade.org/Manual.html（语法核心见 Codeberg 仓库
Manual.md 与官方论坛 sphere 示例：ring / sc8inc / 8sc2inc / 8[sc,sc2inc]）。

许可边界：本模块只输出文本、不引入 CrochetPARADE 代码（其计算组件为
GPLv3，本项目 MIT——保持单向文本出口即可，无需许可合并）。
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from app.models.colors import YARN_COLORS
from app.utils.counts import integer_count as _integer_count

_HEX_BY_NAME = {name: f"#{r:02x}{g:02x}{b:02x}" for (r, g, b), name in YARN_COLORS}

# 翻译器支持的针法词表与 token 白名单（emitter-level lint 用；
# 超出即拒译而非瞎猜——词表来自官方手册的核对于集）
_STITCH_VOCAB = ("sc|hdc|dc|tr|dtr|ch|ss|rsc")
_KNOWN_TOKEN_RE = re.compile(
    rf"^(?:(\d+)(?:\[([^\]]*)\]|({_STITCH_VOCAB})[0-9]*(?:inc|tog)?)"
    rf"|({_STITCH_VOCAB})[0-9]*(?:inc|tog)?)$")
_INNER_TOKEN_RE = re.compile(rf"^(?:\d*({_STITCH_VOCAB})|sc2inc|sc2tog)$")

_HEADER = (
    "# Generated by CrochetPhoto2Pattern — paste into https://crochetparade.org\n"
    "# to render a rotatable 3D model and run its stitch-tension analysis.\n"
    "# Each line is one round; the magic ring (ring) is the anchor row.\n"
)


def _hex_of(color: str | None) -> str | None:
    if not color:
        return None
    if color.startswith("#"):
        return color
    return _HEX_BY_NAME.get(color)


def _round_tokens(prev_stitches: int, rd: dict[str, Any]) -> list[str] | None:
    """把一圈的 (stitches, increase, decrease) 聚合量翻译为 token 序列。

    本项目生成器的圈均为均匀分组（六等分拓扑/钳制），因此：
    - 无加无减：`Nsc`
    - 加针 inc：`M[base_sc,sc2inc]`（M=inc，base=prev//inc-1，需整除）
    - 减针 dec：`M[base_sc,sc2tog]`（M=dec，base=prev//dec-2，需整除）
    返回 None 表示该圈形态超出可译子集（调用方记 warning 并跳过该圈）。
    """
    if not isinstance(rd, dict):
        return None
    try:
        stitches = _integer_count(rd.get("stitches", 0))
        inc = _integer_count(0 if rd.get("increase") is None else rd["increase"])
        dec = _integer_count(0 if rd.get("decrease") is None else rd["decrease"])
    except (ValueError, OverflowError):
        return None
    if stitches < 1 or inc < 0 or dec < 0 or stitches != prev_stitches + inc - dec:
        return None
    if inc and dec:
        return None  # 可钩但超出本导出器的均匀分组子集
    if inc == 0 and dec == 0:
        return [f"{stitches}sc"] if stitches > 0 else None
    groups = inc or dec
    if groups <= 0 or prev_stitches % groups:
        return None
    # 加针组消耗 base+1、产出 base+2；减针组消耗 base+2、产出
    # base+1。两者不能共用同一个 base 偏移。
    base = prev_stitches // groups - (1 if inc else 2)
    if base < 0:
        return None
    produced = groups * (base + 2 if inc else base + 1)
    if produced != stitches:
        return None
    if base == 0:
        return [f"{groups}sc2inc" if inc else f"{groups}sc2tog"]
    base_tok = "sc" if base == 1 else f"{base}sc"  # 对齐官方示例的 8[sc,sc2inc]
    body = f"{base_tok},{'sc2inc' if inc else 'sc2tog'}"
    return [f"{groups}[{body}]"]


@dataclass
class ParadeExportReport:
    text: str = ""
    complete: bool = True
    requested_parts: int = 0  # Physical copies, not logical part definitions.
    exported_parts: int = 0  # Only completely exported copies.
    requested_rounds: int = 0
    exported_rounds: int = 0
    warnings: list[str] = field(default_factory=list)


def _part_lines(part: dict[str, Any], report: ParadeExportReport) -> list[str]:
    """单个部件 → DSL 行；数量 >1 的部件按 start_anew 重复输出。"""
    name = str(part.get("name", "?"))
    warnings = report.warnings
    try:
        quantity = _integer_count(part.get("quantity", 1))
        if not 1 <= quantity <= 20:
            raise ValueError("无效的数量")
    except (ValueError, OverflowError):
        warnings.append(f"{name}: 数量无效，该部件已跳过")
        report.complete = False
        return []
    report.requested_parts += quantity
    rounds = part.get("rounds") or []
    if not isinstance(rounds, list) or not rounds:
        warnings.append(f"{name}: 没有可导出的圈")
        report.complete = False
        return []
    report.requested_rounds += quantity * len(rounds)
    first = rounds[0]
    try:
        n_first = _integer_count(first.get("stitches", 0))
        if n_first < 1:
            raise ValueError("无效的起针数")
    except (AttributeError, ValueError, OverflowError):
        warnings.append(f"{name}: 数量或首圈针数无效，该部件已跳过")
        report.complete = False
        return []
    hex_color = _hex_of(first.get("color")) or _hex_of(part.get("color"))

    lines: list[str] = []
    for copy in range(quantity):
        if copy:
            lines.append("start_anew")
        if hex_color:
            # 每份实体都重置为部件色——多份拷贝不能继承上一份的结尾色
            #（条纹部件 ×N 时尤其重要）
            lines.append(f"COLOR: {hex_color}")
        last_color = hex_color
        # 魔法环行 + 首圈（首圈全部针目放入环：scNinc）
        if not part.get("magic_ring", False):
            warnings.append(
                f"{name}: 首圈非魔法环（{n_first} 针环起），按 ring+sc{n_first}inc 导出，"
                "请对照原说明核对引拔/开口处理")
        lines.append("ring")
        lines.append(f"sc{n_first}inc")
        report.exported_rounds += 1
        prev = n_first
        for index, rd in enumerate(rounds[1:], 2):
            tokens = _round_tokens(prev, rd)
            if tokens is None:
                report.complete = False
                row = rd.get("row", index) if isinstance(rd, dict) else index
                stitches = rd.get("stitches") if isinstance(rd, dict) else "?"
                warnings.append(
                    f"{name} 第 {row} 圈形态超出可译子集"
                    f"（{prev}→{stitches}），该圈及后续圈已跳过")
                # 缺失一次结构变化后，后续 token 即使语法可过 lint，也不再
                # 与最后实际发射圈连续。只导出当前部件的有效前缀，避免用
                # "虚拟前圈"制造一份表面合法、针数却断裂的 DSL。
                break
            color_hex = _hex_of(rd.get("color"))
            # 仅在换色边界输出指令（连续同色圈不重复）——条纹件（如
            # Supergurumi 蜜蜂 55 圈 6 条条纹）从逐圈重复降为每边界一条
            if color_hex and color_hex != last_color:
                lines.append(f"COLOR: {color_hex}")
                last_color = color_hex
            lines.extend(tokens)
            report.exported_rounds += 1
            prev = int(rd.get("stitches", prev))
        else:
            report.exported_parts += 1
    return lines


def lint_parade_dsl(text: str) -> list[str]:
    """emitter-level 静态自检：token 白名单 + 基本结构。

    这不是 CrochetPARADE 官方 parser（其翻译器为 GPL 的 JS/Pyodide 实现，
    不作依赖）；它保证我们的输出落在已核对过的语法子集内。
    """
    issues: list[str] = []
    for i, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("COLOR:") or line.startswith("#"):
            continue
        for tok in [t for t in re.split(r",(?![^\[]*\])", line) if t]:
            token = tok.strip()
            if token in ("ring", "start_anew"):
                continue
            m = _KNOWN_TOKEN_RE.match(token)
            if not m:
                issues.append(f"第 {i} 行无法解析的 token: {token!r}")
                continue
            body = m.group(2)
            if body:
                for inner in body.split(","):
                    inner = inner.strip()
                    if not _INNER_TOKEN_RE.match(inner):
                        issues.append(f"第 {i} 行组内有未知 token: {inner!r}")
    return issues


def export_parade_report(result: dict[str, Any]) -> ParadeExportReport:
    """Return DSL, completeness, physical-copy counts and structured warnings.

    raises:
        ValueError: 结果缺 params.parts 或所有部件都不可译。
    """
    params = result.get("params") or {}
    parts = params.get("parts") or []
    if not isinstance(parts, list) or not parts:
        raise ValueError("结果缺少 params.parts，无法导出 CrochetPARADE DSL")

    report = ParadeExportReport()
    warnings = report.warnings
    body: list[str] = []
    exported_any = False
    for part in parts:
        if not isinstance(part, dict):
            warnings.append("部件格式无效，该部件已跳过")
            report.complete = False
            continue
        lines = _part_lines(part, report)
        if not lines:
            continue
        exported_any = True
        if body:
            body.append("# ── 下一部件 ──")
            body.append("start_anew")
        body.extend(lines)
    if not exported_any:
        raise ValueError("所有部件的圈形态均超出可译子集，未能导出")

    text = _HEADER
    if warnings:
        text += "# 注意（导出器提示）：\n"
        for w in warnings:
            text += f"# - {w}\n"
    text += "\n".join(body) + "\n"
    report.text = text
    return report


def export_parade_dsl(result: dict[str, Any]) -> str:
    """Compatibility text API; partial exports carry warnings in the text."""
    return export_parade_report(result).text
